version: '3.8'

services:
  fomc-classifier:
    build: .
    ports:
      - "8501:8501"  # Streamlit application
    volumes:
      - ./data:/app/data      # Mount your data directory
    environment:
      - EXCEL_PATH=./data/Sentiment&Attributes_Classification.xlsx
    restart: unless-stopped



